<a href="https://colab.research.google.com/github/chmiiin/class2021Spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
%matplotlib inline
from matplotlib import pyplot as plt
import IPython.display as ipd
import numpy as np
from scipy.signal import lfilter

In [ ]:
amp = 1         
sr = 10000      
dur = 0.5        
freq = 300.0

In [21]:
def phasor (amp, sr, dur, freq): 
  t = np.arange(1, sr * dur+1)/sr
  theta = t * 2*np.pi * freq   
  s = np.sin(theta)
  return s, theta, t

In [22]:
phasor (1,10000, 0.5, 300.0)

(array([ 1.87381315e-01,  3.68124553e-01,  5.35826795e-01, ...,
        -3.68124553e-01, -1.87381315e-01, -5.09502587e-14]),
 array([1.88495559e-01, 3.76991118e-01, 5.65486678e-01, ...,
        9.42100805e+02, 9.42289301e+02, 9.42477796e+02]),
 array([1.000e-04, 2.000e-04, 3.000e-04, ..., 4.998e-01, 4.999e-01,
        5.000e-01]))